export interface College {
  id: string;
  name: string;
  state: string;
  city: string;
  stream: string[];
  nirfRank?: number;
  type: 'Government' | 'Private' | 'Deemed';
  website: string;
  courses: string[];
  establishedYear: number;
  description: string;
}

export const indianStates = [
  'Andhra Pradesh',
  'Arunachal Pradesh', 
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Lakshadweep',
  'Puducherry',
  'Andaman and Nicobar Islands'
];

export const streams = [
  'Engineering',
  'Medical',
  'Commerce',
  'Arts & Humanities',
  'Design',
  'Law',
  'Management',
  'Science',
  'Agriculture',
  'Architecture'
];

export const collegeData: College[] = [
  // WEST BENGAL
  {
    id: 'iit-kharagpur',
    name: 'Indian Institute of Technology Kharagpur',
    state: 'West Bengal',
    city: 'Kharagpur',
    stream: ['Engineering'],
    nirfRank: 5,
    type: 'Government',
    website: 'https://www.iitkgp.ac.in',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA'],
    establishedYear: 1951,
    description: 'Premier institute of technology and research with global alumni network.'
  },
  {
    id: 'jadavpur-university',
    name: 'Jadavpur University',
    state: 'West Bengal',
    city: 'Kolkata',
    stream: ['Engineering', 'Arts & Humanities', 'Science'],
    type: 'Government',
    website: 'http://www.jaduniv.edu.in',
    courses: ['B.Tech', 'M.Tech', 'BA', 'MA'],
    establishedYear: 1955,
    description: 'Top multidisciplinary university known for innovation and research.'
  },
  {
    id: 'presidency-university-kolkata',
    name: 'Presidency University',
    state: 'West Bengal',
    city: 'Kolkata',
    stream: ['Arts & Humanities', 'Science'],
    type: 'Government',
    website: 'https://www.presiuniv.ac.in',
    courses: ['BA (Hons)', 'BSc', 'MA', 'MSc'],
    establishedYear: 1817,
    description: 'Prestigious heritage university with strong humanities programs.'
  },
  {
    id: 'calcutta-university',
    name: 'University of Calcutta',
    state: 'West Bengal',
    city: 'Kolkata',
    stream: ['Arts & Humanities', 'Science', 'Commerce'],
    type: 'Government',
    website: 'http://www.caluniv.ac.in',
    courses: ['BA', 'BSc', 'BCom'],
    establishedYear: 1857,
    description: 'One of India\'s oldest universities with over 150 affiliated colleges.'
  },
  {
    id: 'calcutta-medical-college',
    name: 'Calcutta Medical College',
    state: 'West Bengal',
    city: 'Kolkata',
    stream: ['Medical'],
    type: 'Government',
    website: 'https://www.cmchkolkata.org',
    courses: ['MBBS', 'MD', 'MS'],
    establishedYear: 1835,
    description: 'Asia\'s oldest medical college with globally recognized clinical training.'
  },
  {
    id: 'isi-kolkata',
    name: 'Indian Statistical Institute (ISI)',
    state: 'West Bengal',
    city: 'Kolkata',
    stream: ['Science'],
    type: 'Government',
    website: 'https://www.isical.ac.in',
    courses: ['B.Stat', 'M.Stat', 'PhD'],
    establishedYear: 1931,
    description: 'Leading institute specializing in statistics, mathematics, data science.'
  },
  {
    id: 'st-xaviers-kolkata',
    name: 'St. Xavier\'s College, Kolkata',
    state: 'West Bengal',
    city: 'Kolkata',
    stream: ['Arts & Humanities', 'Commerce', 'Science'],
    type: 'Private',
    website: 'https://www.sxccal.edu',
    courses: ['B.Com', 'BA', 'BSc'],
    establishedYear: 1860,
    description: 'Renowned Jesuit college with strong academic and cultural heritage.'
  },
  {
    id: 'iiest-shibpur',
    name: 'IIEST Shibpur',
    state: 'West Bengal',
    city: 'Howrah',
    stream: ['Engineering', 'Science'],
    type: 'Government',
    website: 'https://www.iiests.ac.in',
    courses: ['B.Tech', 'M.Tech', 'PhD'],
    establishedYear: 1856,
    description: 'Historic engineering university with strong research focus.'
  },
  {
    id: 'nit-durgapur',
    name: 'NIT Durgapur',
    state: 'West Bengal',
    city: 'Durgapur',
    stream: ['Engineering', 'Science'],
    type: 'Government',
    website: 'https://www.nitdgp.ac.in',
    courses: ['B.Tech', 'M.Tech', 'PhD'],
    establishedYear: 1960,
    description: 'Premier technical institute with strong industry ties.'
  },
  {
    id: 'visva-bharati',
    name: 'Visva-Bharati University',
    state: 'West Bengal',
    city: 'Santiniketan',
    stream: ['Arts & Humanities', 'Science'],
    type: 'Government',
    website: 'https://www.visvabharati.ac.in',
    courses: ['BA', 'BSc', 'MA'],
    establishedYear: 1921,
    description: 'Founded by Tagore, blending Indian traditions and global academia.'
  },

  // MAHARASHTRA
  {
    id: 'iit-bombay',
    name: 'IIT Bombay',
    state: 'Maharashtra',
    city: 'Mumbai',
    stream: ['Engineering'],
    nirfRank: 1,
    type: 'Government',
    website: 'https://www.iitb.ac.in',
    courses: ['B.Tech', 'M.Tech', 'PhD'],
    establishedYear: 1958,
    description: 'Premier IIT with world-class infrastructure and innovation culture.'
  },
  {
    id: 'university-mumbai',
    name: 'University of Mumbai',
    state: 'Maharashtra',
    city: 'Mumbai',
    stream: ['Arts & Humanities', 'Commerce', 'Science'],
    type: 'Government',
    website: 'http://mu.ac.in',
    courses: ['BA', 'BCom', 'BSc'],
    establishedYear: 1857,
    description: 'One of India\'s oldest universities with large affiliate network.'
  },
  {
    id: 'tiss-mumbai',
    name: 'Tata Institute of Social Sciences (TISS)',
    state: 'Maharashtra',
    city: 'Mumbai',
    stream: ['Arts & Humanities'],
    type: 'Government',
    website: 'https://www.tiss.edu',
    courses: ['MA', 'MSW', 'PhD'],
    establishedYear: 1936,
    description: 'Premier institute for policy, development, and social work.'
  },
  {
    id: 'coep-pune',
    name: 'College of Engineering Pune (COEP)',
    state: 'Maharashtra',
    city: 'Pune',
    stream: ['Engineering'],
    type: 'Government',
    website: 'https://www.coep.org.in',
    courses: ['B.Tech', 'M.Tech', 'PhD'],
    establishedYear: 1854,
    description: 'Historic engineering college with strong research and placements.'
  },
  {
    id: 'pune-university',
    name: 'Savitribai Phule Pune University',
    state: 'Maharashtra',
    city: 'Pune',
    stream: ['Arts & Humanities', 'Science', 'Commerce'],
    type: 'Government',
    website: 'http://www.unipune.ac.in',
    courses: ['BA', 'BSc', 'BCom'],
    establishedYear: 1949,
    description: 'Reputed university with diverse academic programs and research centers.'
  },
  {
    id: 'grant-medical-college',
    name: 'Grant Medical College',
    state: 'Maharashtra',
    city: 'Mumbai',
    stream: ['Medical'],
    type: 'Government',
    website: 'http://www.gmcjjh.org',
    courses: ['MBBS', 'MD', 'MS'],
    establishedYear: 1845,
    description: 'Renowned medical school with advanced clinical training facilities.'
  },
  {
    id: 'symbiosis-pune',
    name: 'Symbiosis International University',
    state: 'Maharashtra',
    city: 'Pune',
    stream: ['Law', 'Management', 'Arts & Humanities'],
    type: 'Private',
    website: 'https://www.siu.edu.in',
    courses: ['BBA', 'LLB', 'MBA'],
    establishedYear: 2002,
    description: 'Top private university offering global-standard education.'
  },
  {
    id: 'nmims-mumbai',
    name: 'NMIMS',
    state: 'Maharashtra',
    city: 'Mumbai',
    stream: ['Management', 'Commerce', 'Engineering'],
    type: 'Private',
    website: 'https://www.nmims.edu',
    courses: ['MBA', 'BBA', 'B.Tech'],
    establishedYear: 1981,
    description: 'Leading private university with strong MBA programs.'
  },
  {
    id: 'fergusson-college',
    name: 'Fergusson College',
    state: 'Maharashtra',
    city: 'Pune',
    stream: ['Arts & Humanities', 'Science'],
    type: 'Government',
    website: 'https://www.fergusson.edu',
    courses: ['BA', 'BSc', 'MA'],
    establishedYear: 1885,
    description: 'Prestigious heritage college known for academics and research.'
  },
  {
    id: 'afmc-pune',
    name: 'AFMC Pune',
    state: 'Maharashtra',
    city: 'Pune',
    stream: ['Medical'],
    type: 'Government',
    website: 'https://afmc.nic.in',
    courses: ['MBBS', 'MD', 'MS'],
    establishedYear: 1948,
    description: 'Elite medical institute for defense forces training.'
  },

  // KARNATAKA
  {
    id: 'iisc-bangalore',
    name: 'IISc Bengaluru',
    state: 'Karnataka',
    city: 'Bengaluru',
    stream: ['Science', 'Engineering'],
    nirfRank: 1,
    type: 'Government',
    website: 'https://www.iisc.ac.in',
    courses: ['BSc (Research)', 'M.Tech', 'PhD'],
    establishedYear: 1909,
    description: 'Premier science and research institution with global ranking.'
  },
  {
    id: 'iit-dharwad',
    name: 'IIT Dharwad',
    state: 'Karnataka',
    city: 'Dharwad',
    stream: ['Engineering'],
    type: 'Government',
    website: 'https://www.iitdh.ac.in',
    courses: ['B.Tech', 'M.Tech', 'PhD'],
    establishedYear: 2016,
    description: 'New IIT with cutting-edge labs and research environment.'
  },
  {
    id: 'nitk-surathkal',
    name: 'NITK Surathkal',
    state: 'Karnataka',
    city: 'Mangaluru',
    stream: ['Engineering'],
    type: 'Government',
    website: 'https://www.nitk.ac.in',
    courses: ['B.Tech', 'M.Tech', 'PhD'],
    establishedYear: 1960,
    description: 'Highly ranked NIT with excellent academics and placements.'
  },
  {
    id: 'bangalore-medical-college',
    name: 'Bangalore Medical College',
    state: 'Karnataka',
    city: 'Bengaluru',
    stream: ['Medical'],
    type: 'Government',
    website: 'https://www.bmcri.org',
    courses: ['MBBS', 'MD', 'MS'],
    establishedYear: 1955,
    description: 'Leading medical college with top clinical facilities.'
  },
  {
    id: 'rv-college-engineering',
    name: 'RV College of Engineering',
    state: 'Karnataka',
    city: 'Bengaluru',
    stream: ['Engineering'],
    type: 'Private',
    website: 'https://www.rvce.edu.in',
    courses: ['B.Tech', 'M.Tech'],
    establishedYear: 1963,
    description: 'Reputed private college with strong placements.'
  },
  {
    id: 'christ-university',
    name: 'Christ University',
    state: 'Karnataka',
    city: 'Bengaluru',
    stream: ['Arts & Humanities', 'Commerce', 'Science', 'Law'],
    type: 'Private',
    website: 'https://www.christuniversity.in',
    courses: ['BA', 'BSc', 'BBA', 'MBA'],
    establishedYear: 1969,
    description: 'Leading private university offering multidisciplinary programs.'
  },
  {
    id: 'st-josephs-bangalore',
    name: 'St. Joseph\'s College',
    state: 'Karnataka',
    city: 'Bengaluru',
    stream: ['Arts & Humanities', 'Science', 'Commerce'],
    type: 'Private',
    website: 'https://www.sjc.ac.in',
    courses: ['BA', 'BSc', 'BCom'],
    establishedYear: 1882,
    description: 'Historic college known for quality undergraduate education.'
  },
  {
    id: 'manipal-mahe',
    name: 'Manipal Academy of Higher Education (MAHE)',
    state: 'Karnataka',
    city: 'Manipal',
    stream: ['Medical', 'Engineering', 'Management'],
    type: 'Private',
    website: 'https://manipal.edu',
    courses: ['MBBS', 'B.Tech', 'MBA'],
    establishedYear: 1953,
    description: 'Internationally reputed private university with global campus.'
  },
  {
    id: 'pes-university',
    name: 'PES University',
    state: 'Karnataka',
    city: 'Bengaluru',
    stream: ['Engineering', 'Management'],
    type: 'Private',
    website: 'https://www.pes.edu',
    courses: ['B.Tech', 'MBA'],
    establishedYear: 1972,
    description: 'Strong placement record and innovative curriculum.'
  },
  {
    id: 'jain-university',
    name: 'Jain University',
    state: 'Karnataka',
    city: 'Bengaluru',
    stream: ['Commerce', 'Arts & Humanities', 'Science'],
    type: 'Private',
    website: 'https://www.jainuniversity.ac.in',
    courses: ['BBA', 'BCA', 'MBA'],
    establishedYear: 1990,
    description: 'Emerging multidisciplinary university with modern programs.'
  },

  // DELHI (NCT)
  {
    id: 'delhi-university',
    name: 'University of Delhi',
    state: 'Delhi',
    city: 'New Delhi',
    stream: ['Arts & Humanities', 'Science', 'Commerce'],
    nirfRank: 2,
    type: 'Government',
    website: 'http://www.du.ac.in',
    courses: ['BA', 'BSc', 'BCom'],
    establishedYear: 1922,
    description: 'Premier university with numerous top colleges in its umbrella.'
  },
  {
    id: 'aiims-delhi',
    name: 'AIIMS Delhi',
    state: 'Delhi',
    city: 'New Delhi',
    stream: ['Medical'],
    nirfRank: 1,
    type: 'Government',
    website: 'https://www.aiims.edu',
    courses: ['MBBS', 'MD', 'MS'],
    establishedYear: 1956,
    description: 'India\'s top medical research and teaching hospital.'
  },
  {
    id: 'iit-delhi',
    name: 'IIT Delhi',
    state: 'Delhi',
    city: 'New Delhi',
    stream: ['Engineering'],
    nirfRank: 2,
    type: 'Government',
    website: 'https://home.iitd.ac.in',
    courses: ['B.Tech', 'M.Tech', 'PhD'],
    establishedYear: 1961,
    description: 'Elite IIT with excellence in research, technology, and placements.'
  },
  {
    id: 'jnu-delhi',
    name: 'JNU',
    state: 'Delhi',
    city: 'New Delhi',
    stream: ['Arts & Humanities', 'Science'],
    nirfRank: 1,
    type: 'Government',
    website: 'https://www.jnu.ac.in',
    courses: ['MA', 'MSc', 'PhD'],
    establishedYear: 1969,
    description: 'Renowned university for multidisciplinary research and humanities.'
  },
  {
    id: 'jamia-millia',
    name: 'Jamia Millia Islamia',
    state: 'Delhi',
    city: 'New Delhi',
    stream: ['Arts & Humanities', 'Engineering', 'Management'],
    type: 'Government',
    website: 'https://www.jmi.ac.in',
    courses: ['BA', 'B.Tech', 'MBA'],
    establishedYear: 1920,
    description: 'Distinguished central university with diverse academic offerings.'
  },
  {
    id: 'dtu-delhi',
    name: 'DTU (Delhi Technological University)',
    state: 'Delhi',
    city: 'New Delhi',
    stream: ['Engineering'],
    type: 'Government',
    website: 'http://dtu.ac.in',
    courses: ['B.Tech', 'M.Tech'],
    establishedYear: 1941,
    description: 'Well-known for practical engineering programs and placements.'
  },
  {
    id: 'nlu-delhi',
    name: 'NLU Delhi',
    state: 'Delhi',
    city: 'New Delhi',
    stream: ['Law'],
    nirfRank: 1,
    type: 'Government',
    website: 'https://nludelhi.ac.in',
    courses: ['BA LLB', 'LLM'],
    establishedYear: 2008,
    description: 'One of the top law schools in India with excellent placements.'
  },
  {
    id: 'srcc-delhi',
    name: 'Sri Ram College of Commerce (SRCC)',
    state: 'Delhi',
    city: 'New Delhi',
    stream: ['Commerce', 'Management'],
    type: 'Government',
    website: 'https://www.srcc.edu',
    courses: ['B.Com', 'BBA'],
    establishedYear: 1926,
    description: 'Premier college for commerce and business education.'
  },
  {
    id: 'lsr-delhi',
    name: 'Lady Shri Ram College (LSR)',
    state: 'Delhi',
    city: 'New Delhi',
    stream: ['Arts & Humanities', 'Commerce'],
    type: 'Government',
    website: 'https://lsr.edu.in',
    courses: ['BA', 'BCom'],
    establishedYear: 1956,
    description: 'Top women\'s college known for quality liberal arts education.'
  },
  {
    id: 'aryabhatta-college',
    name: 'Aryabhatta College, DU',
    state: 'Delhi',
    city: 'New Delhi',
    stream: ['Science', 'Commerce'],
    type: 'Government',
    website: 'http://aryabhattacollege.ac.in',
    courses: ['BSc', 'BCom'],
    establishedYear: 1973,
    description: 'Known for balanced academics and campus engagement.'
  },

  // TAMIL NADU
  {
    id: 'iit-madras',
    name: 'IIT Madras',
    state: 'Tamil Nadu',
    city: 'Chennai',
    stream: ['Engineering'],
    nirfRank: 3,
    type: 'Government',
    website: 'https://www.iitm.ac.in',
    courses: ['B.Tech', 'M.Tech', 'PhD'],
    establishedYear: 1950,
    description: 'Premier IIT with top NIRF rank.'
  },
  {
    id: 'anna-university',
    name: 'Anna University',
    state: 'Tamil Nadu',
    city: 'Chennai',
    stream: ['Engineering'],
    type: 'Government',
    website: 'https://www.annauniv.edu',
    courses: ['B.E.', 'M.Tech'],
    establishedYear: 1978,
    description: 'Leading tech university of Tamil Nadu.'
  },
  {
    id: 'madras-medical-college',
    name: 'Madras Medical College',
    state: 'Tamil Nadu',
    city: 'Chennai',
    stream: ['Medical'],
    type: 'Government',
    website: 'http://www.mmc.ac.in',
    courses: ['MBBS', 'MD', 'MS'],
    establishedYear: 1835,
    description: 'Renowned medical institution with rich history.'
  },
  {
    id: 'university-madras',
    name: 'University of Madras',
    state: 'Tamil Nadu',
    city: 'Chennai',
    stream: ['Arts & Humanities', 'Science', 'Commerce'],
    type: 'Government',
    website: 'https://www.unom.ac.in',
    courses: ['BA', 'BSc', 'BCom'],
    establishedYear: 1857,
    description: 'One of the oldest universities.'
  },
  {
    id: 'nit-trichy',
    name: 'NIT Tiruchirappalli',
    state: 'Tamil Nadu',
    city: 'Tiruchirappalli',
    stream: ['Engineering'],
    type: 'Government',
    website: 'https://www.nitt.edu',
    courses: ['B.Tech', 'M.Tech'],
    establishedYear: 1964,
    description: 'Leading NIT with prestige.'
  },
  {
    id: 'vit-vellore',
    name: 'Vellore Institute of Technology',
    state: 'Tamil Nadu',
    city: 'Vellore',
    stream: ['Engineering'],
    type: 'Private',
    website: 'https://vit.ac.in',
    courses: ['B.Tech', 'M.Tech'],
    establishedYear: 1984,
    description: 'Private technical institution with global presence.'
  },
  {
    id: 'amrita-coimbatore',
    name: 'Amrita Vishwa Vidyapeetham',
    state: 'Tamil Nadu',
    city: 'Coimbatore',
    stream: ['Science', 'Management'],
    type: 'Private',
    website: 'https://www.amrita.edu',
    courses: ['MBA', 'B.Tech'],
    establishedYear: 2003,
    description: 'Deemed university with strong rankings.'
  },
  {
    id: 'tce-madurai',
    name: 'Thiagarajar College of Engineering',
    state: 'Tamil Nadu',
    city: 'Madurai',
    stream: ['Engineering'],
    type: 'Government',
    website: 'https://www.tce.edu',
    courses: ['B.E.', 'M.E.'],
    establishedYear: 1957,
    description: 'Premier engineering college in South.'
  },
  {
    id: 'annamalai-university',
    name: 'Annamalai University',
    state: 'Tamil Nadu',
    city: 'Chidambaram',
    stream: ['Arts & Humanities', 'Science', 'Agriculture'],
    type: 'Government',
    website: 'https://annamalaiuniversity.ac.in',
    courses: ['BA', 'BSc', 'Agriculture'],
    establishedYear: 1929,
    description: 'One of largest residential universities.'
  },
  {
    id: 'nlu-trichy',
    name: 'NLU Tiruchirappalli',
    state: 'Tamil Nadu',
    city: 'Tiruchirappalli',
    stream: ['Law'],
    type: 'Government',
    website: 'https://tnnlu.ac.in',
    courses: ['BA LLB', 'LLM'],
    establishedYear: 2012,
    description: 'National law school of Tamil Nadu.'
  },

  // RAJASTHAN
  {
    id: 'iit-jodhpur',
    name: 'Indian Institute of Technology (IIT) Jodhpur',
    state: 'Rajasthan',
    city: 'Jodhpur',
    stream: ['Engineering'],
    type: 'Government',
    website: 'https://iitj.ac.in',
    courses: ['B.Tech', 'M.Tech'],
    establishedYear: 2008,
    description: 'Premier IIT with emphasis on research and innovation.'
  },
  {
    id: 'university-rajasthan',
    name: 'University of Rajasthan',
    state: 'Rajasthan',
    city: 'Jaipur',
    stream: ['Arts & Humanities', 'Science', 'Commerce'],
    type: 'Government',
    website: 'http://www.uniraj.ac.in',
    courses: ['BA', 'BSc', 'BCom'],
    establishedYear: 1947,
    description: 'One of the oldest universities in Rajasthan with diverse programs.'
  },
  {
    id: 'mnit-jaipur',
    name: 'Malaviya National Institute of Technology (MNIT) Jaipur',
    state: 'Rajasthan',
    city: 'Jaipur',
    stream: ['Engineering'],
    type: 'Government',
    website: 'https://www.mnit.ac.in',
    courses: ['B.Tech', 'M.Tech'],
    establishedYear: 1963,
    description: 'Top-ranked NIT known for excellent academics and placements.'
  },
  {
    id: 'aiims-jodhpur',
    name: 'All India Institute of Medical Sciences (AIIMS) Jodhpur',
    state: 'Rajasthan',
    city: 'Jodhpur',
    stream: ['Medical'],
    type: 'Government',
    website: 'https://www.aiimsjodhpur.edu.in',
    courses: ['MBBS', 'MD', 'MS'],
    establishedYear: 2012,
    description: 'Leading medical and research institute in Western India.'
  },
  {
    id: 'bits-pilani',
    name: 'Birla Institute of Technology & Science (BITS) Pilani',
    state: 'Rajasthan',
    city: 'Pilani',
    stream: ['Engineering', 'Science', 'Management'],
    type: 'Private',
    website: 'https://www.bits-pilani.ac.in',
    courses: ['B.Tech', 'M.Tech', 'MBA'],
    establishedYear: 1964,
    description: 'Renowned for high-quality technical education and research.'
  },
  {
    id: 'raffles-university',
    name: 'Raffles University',
    state: 'Rajasthan',
    city: 'Jaipur',
    stream: ['Law', 'Engineering', 'Management'],
    type: 'Private',
    website: 'https://www.rafflesuniversity.edu.in',
    courses: ['B.Tech', 'LLB', 'MBA'],
    establishedYear: 2011,
    description: 'Young private university with industry-aligned programs.'
  },
  {
    id: 'mgsu-bikaner',
    name: 'Maharaja Ganga Singh University',
    state: 'Rajasthan',
    city: 'Bikaner',
    stream: ['Arts & Humanities', 'Science'],
    type: 'Government',
    website: 'https://mgsubikaner.ac.in',
    courses: ['BA', 'BSc'],
    establishedYear: 2003,
    description: 'Well-established state university with broad academic scope.'
  },
  {
    id: 'ruhs-jaipur',
    name: 'Rajasthan University of Health Sciences (RUHS)',
    state: 'Rajasthan',
    city: 'Jaipur',
    stream: ['Medical'],
    type: 'Government',
    website: 'https://www.ruhsraj.org',
    courses: ['MBBS', 'BPharm', 'MD'],
    establishedYear: 2005,
    description: 'Dedicated university for health science disciplines.'
  },
  {
    id: 'university-kota',
    name: 'University of Kota',
    state: 'Rajasthan',
    city: 'Kota',
    stream: ['Arts & Humanities', 'Science'],
    type: 'Government',
    website: 'https://www.uok.ac.in',
    courses: ['BA', 'BSc'],
    establishedYear: 2003,
    description: 'Major educational institution in eastern Rajasthan.'
  },
  {
    id: 'manipal-jaipur',
    name: 'Manipal University Jaipur',
    state: 'Rajasthan',
    city: 'Jaipur',
    stream: ['Engineering', 'Management'],
    type: 'Private',
    website: 'https://jaipur.manipal.edu',
    courses: ['B.Tech', 'MBA'],
    establishedYear: 2011,
    description: 'Private university with integrated technical and managerial education.'
  },

  // KERALA
  {
    id: 'iist-trivandrum',
    name: 'Indian Institute of Space Science and Technology (IIST)',
    state: 'Kerala',
    city: 'Thiruvananthapuram',
    stream: ['Engineering'],
    type: 'Government',
    website: 'https://www.iist.ac.in',
    courses: ['BTech', 'MTech', 'PhD'],
    establishedYear: 2007,
    description: 'Premier institute focusing on space technology and research.'
  },
  {
    id: 'iiitm-kerala',
    name: 'Indian Institute of Information Technology and Management Kerala (IIITM-K)',
    state: 'Kerala',
    city: 'Thiruvananthapuram',
    stream: ['Engineering', 'Management'],
    type: 'Government',
    website: 'http://www.iiitmk.ac.in',
    courses: ['M.Tech', 'MBA', 'PhD'],
    establishedYear: 2000,
    description: 'Deemed institute for IT, management and applied sciences.'
  },
  {
    id: 'cusat-kochi',
    name: 'Cochin University of Science and Technology (CUSAT)',
    state: 'Kerala',
    city: 'Kochi',
    stream: ['Engineering', 'Science', 'Arts & Humanities'],
    type: 'Government',
    website: 'https://www.cusat.ac.in',
    courses: ['B.Tech', 'M.Tech', 'M.Sc'],
    establishedYear: 1971,
    description: 'Premier university for higher education across disciplines.'
  },
  {
    id: 'kau-thrissur',
    name: 'Kerala Agricultural University',
    state: 'Kerala',
    city: 'Thrissur',
    stream: ['Agriculture', 'Science'],
    type: 'Government',
    website: 'https://www.kau.edu',
    courses: ['BSc (Agri)', 'MSc', 'PhD'],
    establishedYear: 1971,
    description: 'Leading agricultural institute in the state.'
  },
  {
    id: 'gmc-trivandrum',
    name: 'Government Medical College, Thiruvananthapuram',
    state: 'Kerala',
    city: 'Thiruvananthapuram',
    stream: ['Medical'],
    type: 'Government',
    website: 'https://www.gmctvm.nic.in',
    courses: ['MBBS', 'MD'],
    establishedYear: 1951,
    description: 'Historic medical college with strong clinical training.'
  },
  {
    id: 'mgu-kottayam',
    name: 'Mahatma Gandhi University',
    state: 'Kerala',
    city: 'Kottayam',
    stream: ['Arts & Humanities', 'Science', 'Commerce'],
    type: 'Government',
    website: 'https://www.mgu.ac.in',
    courses: ['BA', 'MSc', 'BCom'],
    establishedYear: 1983,
    description: 'Large state university with extensive academic offerings.'
  },
  {
    id: 'nit-calicut',
    name: 'National Institute of Technology Calicut (NIT Calicut)',
    state: 'Kerala',
    city: 'Kozhikode',
    stream: ['Engineering', 'Science'],
    type: 'Government',
    website: 'https://www.nitc.ac.in',
    courses: ['BTech', 'MTech', 'PhD'],
    establishedYear: 2002,
    description: 'Top NIT offering top-tier engineering education.'
  },
  {
    id: 'rajagiri-kochi',
    name: 'Rajagiri College of Social Sciences',
    state: 'Kerala',
    city: 'Kochi',
    stream: ['Arts & Humanities', 'Management'],
    type: 'Private',
    website: 'https://www.rajagiricollege.com',
    courses: ['MSW', 'MBA'],
    establishedYear: 1966,
    description: 'Reputed college for social work and management studies.'
  },
  {
    id: 'ktu-kerala',
    name: 'APJ Abdul Kalam Technological University',
    state: 'Kerala',
    city: 'Thiruvananthapuram',
    stream: ['Engineering'],
    type: 'Government',
    website: 'https://ktu.edu.in',
    courses: ['B.Tech', 'M.Tech'],
    establishedYear: 2014,
    description: 'State tech university coordinating technical education.'
  },
  {
    id: 'rgitkottayam',
    name: 'Rajiv Gandhi Institute of Technology',
    state: 'Kerala',
    city: 'Kottayam',
    stream: ['Engineering'],
    type: 'Government',
    website: 'https://www.rgitkottayam.ac.in',
    courses: ['B.Tech', 'M.Tech'],
    establishedYear: 1991,
    description: 'Leading engineering college under Kerala government.'
  },

  // PUNJAB
  {
    id: 'iit-ropar',
    name: 'Indian Institute of Technology (IIT) Ropar',
    state: 'Punjab',
    city: 'Rupnagar',
    stream: ['Engineering'],
    type: 'Government',
    website: 'https://www.iitrpr.ac.in',
    courses: ['B.Tech', 'M.Tech', 'PhD'],
    establishedYear: 2008,
    description: 'Top IIT focusing on interdisciplinary research.'
  },
  {
    id: 'panjab-university',
    name: 'Panjab University',
    state: 'Punjab',
    city: 'Chandigarh',
    stream: ['Arts & Humanities', 'Science', 'Commerce'],
    type: 'Government',
    website: 'http://www.puchd.ac.in',
    courses: ['BA', 'BSc', 'BCom'],
    establishedYear: 1882,
    description: 'Historic university with wide academic reach.'
  },
  {
    id: 'thapar-patiala',
    name: 'Thapar Institute of Engineering & Technology',
    state: 'Punjab',
    city: 'Patiala',
    stream: ['Engineering'],
    type: 'Private',
    website: 'https://www.thapar.edu',
    courses: ['BTech', 'MTech', 'PhD'],
    establishedYear: 1956,
    description: 'Reputed private engineering institution with strong placements.'
  },
  {
    id: 'cmc-ludhiana',
    name: 'Christian Medical College (CMC) Ludhiana',
    state: 'Punjab',
    city: 'Ludhiana',
    stream: ['Medical'],
    type: 'Private',
    website: 'https://www.cmcludhiana.in',
    courses: ['MBBS', 'MD'],
    establishedYear: 1894,
    description: 'Leading medical institution with clinical excellence.'
  },
  {
    id: 'lpu-phagwara',
    name: 'Lovely Professional University (LPU)',
    state: 'Punjab',
    city: 'Phagwara',
    stream: ['Engineering', 'Management', 'Arts & Humanities'],
    type: 'Private',
    website: 'https://www.lpu.in',
    courses: ['B.Tech', 'MBA', 'BA'],
    establishedYear: 2005,
    description: 'Large private university with global student base.'
  },
  {
    id: 'gndu-amritsar',
    name: 'Guru Nanak Dev University',
    state: 'Punjab',
    city: 'Amritsar',
    stream: ['Arts & Humanities', 'Science'],
    type: 'Government',
    website: 'https://www.gndu.ac.in',
    courses: ['BA', 'BSc'],
    establishedYear: 1969,
    description: 'Significant public university with diverse programs.'
  },
  {
    id: 'nift-jalandhar',
    name: 'National Institute of Fashion Technology (NIFT) Jalandhar',
    state: 'Punjab',
    city: 'Jalandhar',
    stream: ['Design'],
    type: 'Government',
    website: 'https://www.nift.ac.in/jalandhar',
    courses: ['BDes', 'MDes'],
    establishedYear: 1995,
    description: 'Premier fashion and design institute.'
  },
  {
    id: 'rayat-bahra',
    name: 'Rayat Bahra University',
    state: 'Punjab',
    city: 'Mohali',
    stream: ['Engineering', 'Management'],
    type: 'Private',
    website: 'https://www.rayatbahra.com',
    courses: ['B.Tech', 'MBA'],
    establishedYear: 2006,
    description: 'Emerging private university with technical and business programs.'
  },
  {
    id: 'dav-jalandhar',
    name: 'DAV College, Jalandhar',
    state: 'Punjab',
    city: 'Jalandhar',
    stream: ['Arts & Humanities', 'Commerce'],
    type: 'Private',
    website: 'https://www.davjalandhar.ac.in',
    courses: ['BA', 'BCom'],
    establishedYear: 1918,
    description: 'Renowned college with strong educational heritage.'
  },
  {
    id: 'lcet-ludhiana',
    name: 'Ludhiana College of Engineering and Technology',
    state: 'Punjab',
    city: 'Ludhiana',
    stream: ['Engineering'],
    type: 'Private',
    website: 'https://lcet.ac.in',
    courses: ['B.Tech'],
    establishedYear: 2008,
    description: 'Well-known regional engineering college.'
  },

  // HARYANA
  {
    id: 'nit-kurukshetra',
    name: 'National Institute of Technology (NIT) Kurukshetra',
    state: 'Haryana',
    city: 'Kurukshetra',
    stream: ['Engineering'],
    type: 'Government',
    website: 'https://www.nitkkr.ac.in',
    courses: ['B.Tech', 'M.Tech', 'PhD'],
    establishedYear: 1963,
    description: 'Highly regarded NIT with strong core engineering programs.'
  },
  {
    id: 'mdu-rohtak',
    name: 'Maharshi Dayanand University (MDU)',
    state: 'Haryana',
    city: 'Rohtak',
    stream: ['Arts & Humanities', 'Commerce', 'Science'],
    type: 'Government',
    website: 'https://www.mdu.ac.in',
    courses: ['BA', 'BSc', 'BCom'],
    establishedYear: 1976,
    description: 'Solid state university with wide regional access.'
  },
  {
    id: 'gjust-hisar',
    name: 'Guru Jambheshwar University of Science and Technology',
    state: 'Haryana',
    city: 'Hisar',
    stream: ['Engineering', 'Science'],
    type: 'Government',
    website: 'https://www.gjust.ac.in',
    courses: ['B.Tech', 'M.Tech'],
    establishedYear: 1995,
    description: 'Good technical university offering modern courses.'
  },
  {
    id: 'manav-rachna',
    name: 'Manav Rachna International Institute of Research & Studies',
    state: 'Haryana',
    city: 'Faridabad',
    stream: ['Engineering', 'Management'],
    type: 'Private',
    website: 'https://www.manavrachna.edu.in',
    courses: ['B.Tech', 'MBA'],
    establishedYear: 2014,
    description: 'Emerging private institution with global focus.'
  },

  // GUJARAT
  {
    id: 'iim-ahmedabad',
    name: 'Indian Institute of Management Ahmedabad',
    state: 'Gujarat',
    city: 'Ahmedabad',
    stream: ['Management'],
    nirfRank: 1,
    type: 'Government',
    website: 'https://www.iima.ac.in',
    courses: ['PGP', 'MBA', 'Executive MBA', 'Fellow Programme'],
    establishedYear: 1961,
    description: 'Premier management institute with global recognition and excellent placements.'
  },
  {
    id: 'nid-ahmedabad',
    name: 'National Institute of Design Ahmedabad',
    state: 'Gujarat',
    city: 'Ahmedabad',
    stream: ['Design'],
    nirfRank: 1,
    type: 'Government',
    website: 'https://www.nid.edu',
    courses: ['Product Design', 'Communication Design', 'Textile Design', 'Animation'],
    establishedYear: 1961,
    description: 'Premier design institute fostering creativity and innovation in design education.'
  },

  // UTTAR PRADESH
  {
    id: 'iit-kanpur',
    name: 'Indian Institute of Technology Kanpur',
    state: 'Uttar Pradesh',
    city: 'Kanpur',
    stream: ['Engineering'],
    nirfRank: 4,
    type: 'Government',
    website: 'https://www.iitk.ac.in',
    courses: ['Computer Science', 'Mechanical Engineering', 'Materials Science', 'Aerospace Engineering'],
    establishedYear: 1959,
    description: 'Prestigious IIT with strong emphasis on research and development.'
  },

  // TELANGANA 
  {
    id: 'nalsar-hyderabad',
    name: 'NALSAR University of Law',
    state: 'Telangana',
    city: 'Hyderabad',
    stream: ['Law'],
    nirfRank: 2,
    type: 'Government',
    website: 'https://www.nalsar.ac.in',
    courses: ['BA LLB', 'LLM', 'PhD', 'MBA'],
    establishedYear: 1998,
    description: 'Leading law university in South India with excellent academic programs.'
  },

  // CHANDIGARH
  {
    id: 'pgimer-chandigarh',
    name: 'Post Graduate Institute of Medical Education and Research',
    state: 'Chandigarh',
    city: 'Chandigarh',
    stream: ['Medical'],
    nirfRank: 2,
    type: 'Government',
    website: 'https://www.pgimer.edu.in',
    courses: ['MBBS', 'MD', 'MS', 'DM', 'MCh'],
    establishedYear: 1962,
    description: 'Leading medical institute in North India with advanced healthcare facilities.'
  }
];